apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend-secret
spec:
  provider:
    vault:
      server: https://vault.naidu72.info
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes-pi5
          role: eso-role
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
